"""empty message

Revision ID: 713136b66f9e
Revises: 2f40b0b9b455
Create Date: 2023-03-12 17:18:43.772413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713136b66f9e'
down_revision = '2f40b0b9b455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_data', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
