"""empty message

Revision ID: 80d53f367b0b
Revises: bc99cc8217cb
Create Date: 2023-03-12 20:38:13.039673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d53f367b0b'
down_revision = 'bc99cc8217cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_data', schema=None) as batch_op:
        batch_op.alter_column('bedrooms',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=True)
        batch_op.alter_column('bathrooms',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=80),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_data', schema=None) as batch_op:
        batch_op.alter_column('bathrooms',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('bedrooms',
               existing_type=sa.String(length=80),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
